code/altemoi/altemoi/altemoi/altemoi/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('terminal/', include('terminal.urls', namespace = "terminal")),
    path('usuarios/', include('usuarios.urls', namespace= "usuarios")),
    path('', LoginView.as_view(template_name='index.html'), name = "login"),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('reset/password_reset', PasswordResetView.as_view(template_name='registration/password_reset_form.html', email_template_name='registration/password_reset_email.html'), name = 'password_reset'),
    path('reset/password_reset_done', PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name = 'password_reset_done'),
    re_path(r'^reset/(?P<uidb64>[0-9A-za-z_\-]+)/(?P<token>.+)/$', PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name = 'password_reset_confirm'),
    path('reset/done',PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html') , name = 'password_reset_complete'),
]

code/altemoi/altemoi/altemoi/terminal/urls.py
from django.urls import include, path, re_path
from django.contrib.auth.decorators import login_required

from . import views
app_name = "terminal"

urlpatterns = [
                path('tablon', login_required(views.Tablon), name='tablon'),

                #vista de monitor de Entradas y Salidas
                path('monitor', login_required(views.Monitor), name='monitor'),
                path('vermonitor', login_required(views.VerMonitor), name='vermonitor'),
                path('nuevaterminal', login_required(views.NuevaTerminal.as_view()), name='nueva_lvidaqa'),
                path('listaterminal', login_required(views.ListaTerminal.as_view()), name='lista_lvidaqa'),
                re_path(r'^editarterminal/(?P<pk>\d+)/$', login_required(views.EditarTerminal.as_view()), name='editar_lvidaqa'),
                re_path(r'^eliminarterminal/(?P<pk>\d+)/$', login_required(views.EliminarTerminal.as_view()), name='eliminar_lvidaqa'),


                path('nuevapuerta', login_required(views.NuevaPuerta.as_view()), name='nueva_lasom'),
                path('listapuerta', login_required(views.ListaPuerta.as_view()), name='lista_lasom'),
                re_path(r'^editarpuerta/(?P<pk>\d+)/$', login_required(views.EditarPuerta.as_view()), name='editar_lasom'),
                re_path(r'^eliminarpuerta/(?P<pk>\d+)/$', login_required(views.EliminarPuerta.as_view()), name='eliminar_lasom'),


                path('nuevaplataforma', login_required(views.NuevaPlataforma.as_view()), name='nueva_lmala'),
                path('listaplataforma', login_required(views.ListaPlataforma.as_view()), name='lista_lmala'),
                re_path(r'^editarplataforma/(?P<pk>\d+)/$', login_required(views.EditarPlataforma.as_view()), name='editar_lmala'),
                re_path(r'^eliminarplataforma/(?P<pk>\d+)/$', login_required(views.EliminarPlataforma.as_view()), name='eliminar_lmala'),


                path('nuevaboleteria', login_required(views.NuevaBoleteria.as_view()), name='nueva_nmen'),
                path('listaboleteria', login_required(views.ListaBoleteria.as_view()), name='lista_nmen'),
                re_path(r'^editarboleteria/(?P<pk>\d+)/$', login_required(views.EditarBoleteria.as_view()), name='editar_nmen'),
                re_path(r'^eliminarboleteria/(?P<pk>\d+)/$', login_required(views.ElimininarBoleteria.as_view()), name='eliminar_nmen'), #falta implementar esto


                path('nuevostatus', login_required(views.NuevoStatus.as_view()), name='nuevo_status'),
                path('listastatus', login_required(views.ListaStatus.as_view()), name='lista_status'),
                re_path(r'^editarstatus/(?P<pk>\d+)/$', login_required(views.EditarStatus.as_view()), name='editar_status'),
                re_path(r'^eliminarstatus/(?P<pk>\d+)/$', login_required(views.EliminarStatus.as_view()), name='eliminar_status'),

                #paths para configuración de países, provincias, ciudades

                #países
                path('nuevopais', login_required(views.NuevoPais.as_view()), name='nuevo_alhua'),
                path('listapais', login_required(views.ListaPais.as_view()), name='lista_alhua'),
                re_path(r'^editarpais/(?P<pk>\d+)/$', login_required(views.EditarPais.as_view()), name='editar_alhua'),
                re_path(r'^eliminarpais/(?P<pk>\d+)/$', login_required(views.EliminarPais.as_view()), name='eliminar_alhua'),

                #provincias
                path('nuevaprovincia', login_required(views.NuevaProvincia.as_view()), name='nueva_alhuana'),
                path('listaprovincia', login_required(views.ListaProvincia.as_view()), name='lista_alhuana'),
                re_path(r'^editarprovincia/(?P<pk>\d+)/$', login_required(views.EditarProvincia.as_view()), name='editar_alhuana'),
                re_path(r'^eliminarprovincia/(?P<pk>\d+)/$', login_required(views.EliminarProvincia.as_view()), name='eliminar_alhuana'),

                #ciudades
                path('nuevaciudad', login_required(views.NuevaCiudad.as_view()), name='nueva_yinoyic'),
                path('listaciudad', login_required(views.ListaCiudad.as_view()), name='lista_yinoyic'),
                re_path(r'^editarciudad/(?P<pk>\d+)/$', login_required(views.EditarCiudad.as_view()), name='editar_yinoyic'),
                re_path(r'^eliminarciudad/(?P<pk>\d+)/$', login_required(views.EliminarCiudad.as_view()), name='eliminar_yinoyic'),


                #empresas de transporte
                path('nuevaempresa', login_required(views.NuevaEmpresa.as_view()), name='nueva_iqueuoxon'),
                path('listaempresa', login_required(views.ListaEmpresa.as_view()), name='lista_iqueuoxon'),
                re_path(r'^verempresa/(?P<pk>\d+)/$', login_required(views.VerEmpresa.as_view()), name='ver_iqueuoxon'),
                re_path(r'^editarempresa/(?P<pk>\d+)/$', login_required(views.EditarEmpresa.as_view()), name='editar_iqueuoxon'),
                re_path(r'^eliminarempresa/(?P<pk>\d+)/$', login_required(views.EliminarEmpresa.as_view()), name='eliminar_iqueuoxon'),

                #servicios de transporte ingresantes
                path('nuevoingreso', login_required(views.NuevoIngreso.as_view()), name='nuevo_inoxoneuo'),
                path('listaingreso', login_required(views.ListaIngreso.as_view()), name='lista_inoxoneuo'),
                re_path(r'^editaringreso/(?P<pk>\d+)/$', login_required(views.EditarIngreso.as_view()), name='editar_inoxoneuo'),
                re_path(r'^eliminaringreso/(?P<pk>\d+)/$', login_required(views.EliminarIngreso.as_view()), name='eliminar_inoxoneuo'),

                #Detalle del servicio ingresante
                #la forma de llamarla es levemente diferente porque es una vista basada en función
                path('detalleingreso/<int:id_ingreso>/', login_required(views.DetalleIngreso), name='detalle_inoxoneuo'),
                path('nuevoingresointermedio/<int:id_ingreso>/', login_required(views.NuevoIngresoIntermedio), name='nuevo_inoxoneuo_intermedio'),
                re_path(r'^eliminaringresointermedio/(?P<pk>\d+)/$', login_required(views.EliminarIngresoIntermedio.as_view()), name='eliminar_inoxoneuo_intermedio'),

                #Detalle del servicio saliente
                #la forma de llamarla es levemente diferente porque es una vista basada en función
                path('detalleegreso/<int:id_egreso>/', login_required(views.DetalleEgreso), name='detalle_deyachi'),
                path('nuevoegresointermedio/<int:id_egreso>/', login_required(views.NuevoEgresoIntermedio), name='nuevo_deyachi_intermedio'),
                re_path(r'^eliminaregresointermedio/(?P<pk>\d+)/$', login_required(views.EliminarEgresoIntermedio.as_view()), name='eliminar_deyachi_intermedio'),

                #paths para asociar empresas a boleterías
                #path('nuevaboleteriaempresa', login_required(views.NuevaBoleteriaEmpresa.as_view()), name='nuevo_nmen_iqueuoxon'),
                path('nuevaboleteriaempresa/<int:id_boleteria>/', login_required(views.NuevaBoleteriaEmpresa), name='nuevo_nmen_iqueuoxon'),
                re_path(r'^verboleteria/(?P<pk>\d+)/$', login_required(views.VerBoleteria.as_view()), name='ver_nmen'),
                path('listaboleteriaempresa/<int:id_boleteria>/', login_required(views.ListaBoleteriaEmpresa), name='lista_nmen_iqueuoxon'),
                re_path(r'^eliminarboleteriaempresa/(?P<pk>\d+)/$', login_required(views.EliminarBoleteriaEmpresa.as_view()), name='eliminar_nmen_iqueuoxon'),


                #servicios de transporte salientes
                path('nuevoegreso', login_required(views.NuevoEgreso.as_view()), name='nuevo_deyachi'),
                path('listaegreso', login_required(views.ListaEgreso.as_view()), name='lista_deyachi'),
                #path('listaegreso', login_required(views.ListaEgreso), name='lista_deyachi'),
                re_path(r'^editaregreso/(?P<pk>\d+)/$', login_required(views.EditarEgreso.as_view()), name='editar_deyachi'),
                re_path(r'^eliminaregreso/(?P<pk>\d+)/$', login_required(views.EliminarEgreso.as_view()), name='eliminar_deyachi'),



                #parámetros del Sistema
                path('nuevoparametro', login_required(views.NuevoParametro.as_view()), name='nuevo_parametro'),
                path('listaparametro', login_required(views.ListaParametro.as_view()), name='lista_parametro'),
                re_path(r'^editarparametro/(?P<pk>\d+)/$', login_required(views.EditarParametro.as_view()), name='editar_parametro'),
                re_path(r'^eliminarparametro/(?P<pk>\d+)/$', login_required(views.EliminarParametro.as_view()), name='eliminar_parametro'),

]

code/altemoi/altemoi/altemoi/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('terminal/', include('terminal.urls', namespace = "terminal")),
    path('usuarios/', include('usuarios.urls', namespace= "usuarios")),
    path('', LoginView.as_view(template_name='index.html'), name = "login"),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('reset/password_reset', PasswordResetView.as_view(template_name='registration/password_reset_form.html', email_template_name='registration/password_reset_email.html'), name = 'password_reset'),
    path('reset/password_reset_done', PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name = 'password_reset_done'),
    re_path(r'^reset/(?P<uidb64>[0-9A-za-z_\-]+)/(?P<token>.+)/$', PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name = 'password_reset_confirm'),
    path('reset/done',PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html') , name = 'password_reset_complete'),
]

code/altemoi/altemoi/altemoi/templates/nachaxan/alhua.html
{%  extends 'nachaxan/base.html' %}

{% block titulo_lista %} <i class="bi bi-geo-alt"></i> Configuración - Países{% endblock %}

{% block boton_superior %}
  <div>
    <button class="btn btn-outline-success" onclick="nuevo_registro_modal('{% url 'terminal:nuevo_alhua' %}')" name="button">Agregar país</button>

  </div>
{% endblock %}

{% block lista_contenido %}



<table id="tabla" class='table table-striped'>
  <thead>
    <tr>
      <td>#</td>
      <td>Denominación</td>
      <td>Código</td>
      <td>Acciones</td>
    </tr>
  </thead>
  <tbody>
    <!-- Veo si hay registros de terminales para mostrar-->
    {% if object_list %}
      {% for pais in object_list %}
        <tr>
          <td>{{pais.id}}</td>
          <td>{{pais.denominacion}}</td>
          <td>{{pais.code}}</td>
          <td>
            <div class="dropdown">
             <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
               Acciones
             </button>
             <div class="dropdown-menu">
                 <button class="dropdown-item" onclick="editar_registro_modal('{% url 'terminal:editar_alhua' pais.id %}')">Editar</button>
                 <button class="dropdown-item" onclick="eliminar_registro_modal('{% url 'terminal:eliminar_alhua' pais.id %}')">Eliminar</button>
             </div>

          </div>
          </td>
        </tr>
      {% endfor %}
    {% else %}
    <h1>No hay países registrados en el sistema</h1>
    <button class="btn btn-outline-success" onclick="nuevo_registro_modal('{% url 'terminal:nuevo_alhua' %}')" name="button">Agregar país</button>
    {% endif %}
  </tbody>
</table>

{% endblock %}

code/altemoi/altemoi/altemoi/templates/nachaxan/deyachiintermedio.html
{%  extends 'nachaxan/base.html' %}

{% block titulo_lista %} Detalle del servicio saliente {% endblock %}

{% block boton_superior %}


  <div class="container p-5 my-5 border">
    <h3>Detalle del viaje de empresa {{egreso.empresa}} con destino a {{egreso.destino}}</h3>

    <div class="row border-bottom">
      <div class="col-sm-6 col-md-3 bg-info">
        <p>Empresa</p>
      </div>

      <div class="col-sm-6 col-md-3 border-right">
        <p>{{egreso.empresa}}</p>
      </div>



      <div class="col-sm-6 col-md-3 bg-info">
        <p>Origen</p>
      </div>

      <div class="col-sm-6 col-md-3">
        <p>{{egreso.origen}}</p>
      </div>
    </div>
    <div class="row border-top border-bottom">
      <div class="col-sm-6 col-md-3 bg-info">
        <p>Hora de partida en Terminal</p>
      </div>

      <div class="col-sm-6 col-md-3">
        <!--Averiguar si se puede hacer que devuelva "No establecido" directamente desde el modelo -->

        <p>{{egreso.horaPartida}}</p>

      </div>

      <div class="col-sm-6 col-md-3 bg-info">
        <p>Hora de arribo a terminal</p>
      </div>

      <div class="col-sm-6 col-md-3">
        <p>{% if egreso.horaArribo %}{{egreso.horaArribo}} {% else %} No establecido {% endif %}</p>

      </div>

    </div>

    <button class="btn btn-outline-success" onclick="nuevo_registro_modal('{% url 'terminal:nuevo_deyachi_intermedio' egreso.id %}')" name="button">Agregar ciudad intermedia</button>
    <!--
    <a class="btn btn-outline-success" href="{% url 'terminal:nuevo_inoxoneuo' %}" name="button">Agregar ciudad intermedia</a>
    -->

  </div>
{% endblock %}

{% block lista_contenido %}



<table id="tabla" class='table table-striped'>
  <thead>
    <tr>
      <td>#</td>
      <td>Ciudad</td>
      <td>Acciones</td>
    </tr>
  </thead>
  <tbody>
    <!-- Veo si hay registros de terminales para mostrar-->
    {% if intermedios %}
      {% for i in intermedios %}
        <tr>
          <td>{{i.id}}</td>
          <td>{{i.ciudad.denominacion}}</td>


            <td>
              <a class="btn btn-danger" href="{% url 'terminal:eliminar_deyachi_intermedio' i.id %}" data-bs-toggle="tooltip" title="Eliminar"><i class="bi bi-trash"></i></a>
            </td>


        </tr>
      {% endfor %}
    {% else %}
    <h1>No hay ciudades intermedias registradas en el sistema.</h1>
        <button class="btn btn-outline-success" onclick="nuevo_registro_modal('{% url 'terminal:nuevo_deyachi_intermedio' egreso.id %}')" name="button">Agregar ciudad intermedia</button>
    {% endif %}
  </tbody>
</table>

{% endblock %}

code/altemoi/altemoi/altemoi/templates/nachaxan/inoxoneuo.html
{%  extends 'nachaxan/base.html' %}

{% block titulo_lista %} <i class="bi bi-box-arrow-in-up-right"></i>
Servicios entrantes {% endblock %}

{% block boton_superior %}
  <div>
    <!--
    <button class="btn btn-outline-success" onclick="nuevo_registro_modal('{% url 'terminal:nuevo_inoxoneuo' %}')" name="button">Agregar servicio ingresante</button>
    -->
    <a class="btn btn-outline-success" href="{% url 'terminal:nuevo_inoxoneuo' %}" name="button">

      Agregar servicio ingresante</a>

  </div>
{% endblock %}

{% block lista_contenido %}



<table id="tabla" class='table table-striped'>
  <thead>
    <tr>
      <td>#</td>
      <td>Empresa</td>
      <td>Origen</td>
      <td>Escalas</td>
      <td>Hora arribo</td>
      <td>D</td>
      <td>L</td>
      <td>M</td>
      <td>X</td>
      <td>J</td>
      <td>V</td>
      <td>S</td>
      <td>Acciones</td>
    </tr>
  </thead>
  <tbody>
    <!-- Veo si hay registros de terminales para mostrar-->
    {% if object_list %}
      {% for arribo in object_list %}
        <tr>
          <td>{{arribo.id}}</td>
          <td>{{arribo.empresa.razonSocial}}</td>
          <td>{{arribo.origen}}</td>
          <td>


            {% for intermedio in arribo.inoxoneuointermedio_set.all %}
              <small>{{intermedio.ciudad.denominacion}}</small>
            {% endfor %}

          </td>
          <td>{{arribo.horaArribo}}</td>
          <td>{% if arribo.d %}<span class="badge badge-success">D</span>{% endif %}</td>
          <td>{% if arribo.l %}<span class="badge badge-success">L</span>{% endif %}</td>
          <td>{% if arribo.m %}<span class="badge badge-success">M</span>{% endif %}</td>
          <td>{% if arribo.x %}<span class="badge badge-success">X</span>{% endif %}</td>
          <td>{% if arribo.j %}<span class="badge badge-success">J</span>{% endif %}</td>
          <td>{% if arribo.v %}<span class="badge badge-success">V</span>{% endif %}</td>
          <td>{% if arribo.s %}<span class="badge badge-success">S</span>{% endif %}</td>
          <td>
            <div class="dropdown">
             <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
               Acciones
             </button>
             <div class="dropdown-menu">
                <!--

                 <button class="dropdown-item" onclick="editar_registro_modal('{% url 'terminal:editar_inoxoneuo' arribo.id %}')">Editar</button>
                 <button class="dropdown-item" onclick="eliminar_registro_modal('{% url 'terminal:eliminar_inoxoneuo' arribo.id %}')">Eliminar</button>
                 -->
                 <a class="dropdown-item" href="{% url 'terminal:detalle_inoxoneuo' arribo.id %}">Detalles</a>
                 <a class="dropdown-item" href="{% url 'terminal:editar_inoxoneuo' arribo.id %}">Editar</a>
                 <button class="dropdown-item" onclick="eliminar_registro_modal('{% url 'terminal:eliminar_inoxoneuo' arribo.id %}')">Eliminar</button>
             </div>
          </div>
          </td>
        </tr>
      {% endfor %}
    {% else %}
    <h1>No hay arribos registrados en el sistema</h1>
        <button class="btn btn-outline-success" onclick="nuevo_registro_modal('{% url 'terminal:nuevo_inoxoneuo' %}')" name="button">Agregar servicio ingresante</button>
    {% endif %}
  </tbody>
</table>

{% endblock %}

code/altemoi/altemoi/altemoi/templates/nachaxan/inoxoneuointermedio.html
{%  extends 'nachaxan/base.html' %}

{% block titulo_lista %} Detalle del servicio entrante {% endblock %}

{% block boton_superior %}


  <div class="container p-5 my-5 border">
    <h3>Detalle del viaje de empresa {{ingreso.empresa}} proveniente de {{ingreso.origen}}</h3>

    <div class="row border-bottom">
      <div class="col-sm-6 col-md-3 bg-info">
        <p>Empresa</p>
      </div>

      <div class="col-sm-6 col-md-3 border-right">
        <p>{{ingreso.empresa}}</p>
      </div>



      <div class="col-sm-6 col-md-3 bg-info">
        <p>Origen</p>
      </div>

      <div class="col-sm-6 col-md-3">
        <p>{{ingreso.origen}}</p>
      </div>
    </div>
    <div class="row border-top border-bottom">
      <div class="col-sm-6 col-md-3 bg-info">
        <p>Hora de partida en origen</p>
      </div>

      <div class="col-sm-6 col-md-3">
        <!--Averiguar si se puede hacer que devuelva "No establecido" directamente desde el modelo -->

        <p>{% if ingreso.horaPartida %}{{ingreso.horaPartida}} {% else %} No establecido {% endif %}</p>

      </div>

      <div class="col-sm-6 col-md-3 bg-info">
        <p>Hora de arribo a terminal</p>
      </div>

      <div class="col-sm-6 col-md-3">
        <p>{{ingreso.horaArribo}}</p>
      </div>

    </div>

    <button class="btn btn-outline-success" onclick="nuevo_registro_modal('{% url 'terminal:nuevo_inoxoneuo_intermedio' ingreso.id %}')" name="button">Agregar ciudad intermedia</button>
    <!--
    <a class="btn btn-outline-success" href="{% url 'terminal:nuevo_inoxoneuo' %}" name="button">Agregar ciudad intermedia</a>
    -->

  </div>
{% endblock %}

{% block lista_contenido %}



<table id="tabla" class='table table-striped'>
  <thead>
    <tr>
      <td>#</td>
      <td>Ciudad</td>
      <td>Acciones</td>
    </tr>
  </thead>
  <tbody>
    <!-- Veo si hay registros de terminales para mostrar-->
    {% if intermedios %}
      {% for i in intermedios %}
        <tr>
          <td>{{i.id}}</td>
          <td>{{i.ciudad.denominacion}}</td>


            <td>
              <a class="btn btn-danger" href="{% url 'terminal:eliminar_inoxoneuo_intermedio' i.id %}" data-bs-toggle="tooltip" title="Eliminar"><i class="bi bi-trash"></i></a>
            </td>

          
        </tr>
      {% endfor %}
    {% else %}
    <h1>No hay ciudades intermedias registradas en el sistema.</h1>
        <button class="btn btn-outline-success" onclick="nuevo_registro_modal('{% url 'terminal:nuevo_inoxoneuo_intermedio' ingreso.id %}')" name="button">Agregar ciudad intermedia</button>
    {% endif %}
  </tbody>
</table>

{% endblock %}

code/altemoi/altemoi/altemoi/templates/nachaxan/iqueuoxon.html
{%  extends 'nachaxan/base.html' %}

{% block titulo_lista %} Configuración - Empresas de transporte {% endblock %}

{% block boton_superior %}
  <div>
    <button class="btn btn-outline-success" onclick="nuevo_registro_modal('{% url 'terminal:nueva_iqueuoxon' %}')" name="button">Agregar empresa de transporte</button>

  </div>
{% endblock %}

{% block lista_contenido %}



<table id="tabla" class='table table-striped'>
  <thead>
    <tr>
      <td>#</td>
      <td>Razón social</td>
      <td>CUIT</td>
      <td>Acciones</td>
    </tr>
  </thead>
  <tbody>
    <!-- Veo si hay registros de terminales para mostrar-->
    {% if object_list %}
      {% for empresa in object_list %}
        <tr>
          <td>{{empresa.id}}</td>
          <td>{{empresa.razonSocial}}</td>
          <td>{{empresa.nro_impositivo}}</td>
          <td>
            <button class="btn btn-success" onclick="editar_registro_modal('{% url 'terminal:ver_iqueuoxon' empresa.id %}')"><i class="bi bi-eye"></i></button>
            <button class="btn btn-warning" onclick="editar_registro_modal('{% url 'terminal:editar_iqueuoxon' empresa.id %}')"><i class="bi bi-pencil-square"></i></button>
            <button class="btn btn-danger" onclick="editar_registro_modal('{% url 'terminal:eliminar_iqueuoxon' empresa.id %}')"><i class="bi bi-trash"></i></button>


          </td>
        </tr>
      {% endfor %}
    {% else %}
    <h1>No hay empresas registradas en el sistema</h1>
    <a class="btn btn-outline-success" href="{% url 'terminal:nueva_iqueuoxon' %}">Agregar empresa</a>
    {% endif %}
  </tbody>
</table>

{% endblock %}

code/altemoi/altemoi/altemoi/templates/nachaxan/nmen.html
{%  extends 'nachaxan/base.html' %}

{% block titulo_lista %} Servicios entrantes {% endblock %}


{% block boton_superior %}
  <div>

    <a class="btn btn-outline-success" href="{% url 'terminal:nueva_nmen' %}" name="button">Agregar boletería</a>

  </div>
{% endblock %}


{% block lista_contenido %}

<table id="listadoBoleterias" class='table table-striped'>
  <thead>
    <tr>
      <td>#</td>
      <td>Terminal</td>
      <td>Identificador</td>
      <td>Teléfono público</td>
      <td>Interno</td>
      <td>Correo electrónico</td>
      <td>Persona contacto</td>
      <td>Teléfono urgencia</td>
      <td>Estado</td>
      <td>Acciones</td>
    </tr>
  </thead>
  <tbody>
    <!-- Veo si hay registros de boleterías para mostrar-->
    {% if object_list %}
      {% for boleteria in object_list %}
        <tr>
          <td>{{boleteria.id}}</td>
          <td>{{boleteria.terminal.denominacion}}</td>
          <td>{{boleteria.numeroID}}</td>
          <td>{{boleteria.telefono}}</td>
          <td>{{boleteria.internoTelefono}}</td>
          <td>{{boleteria.email}}</td>
          <td>{{boleteria.nombreContacto}}</td>
          <td>{{boleteria.telefonoEmergencia}}</td>
          <td style="color:{{boleteria.status.color}}; font-weight: bold; ">{{boleteria.status.denominacion}}</td>
          <td>
            <button class="btn btn-success" onclick="editar_registro_modal('{% url 'terminal:ver_nmen' boleteria.id %}')"><i class="bi bi-eye"></i></button>
            <a class="btn btn-success" href="{% url 'terminal:editar_nmen' boleteria.id %}" data-bs-toggle="tooltip" title="Modificar"><i class="bi bi-pencil-square"></i></a>
            <a class="btn btn-warning" href="{% url 'terminal:lista_nmen_iqueuoxon' boleteria.id %}" data-bs-toggle="tooltip" title="Asociar empresas"><i class="bi bi-plus-lg"></i>Empresas</a>

            <a class="btn btn-danger" href="{% url 'terminal:eliminar_nmen' boleteria.id %}" data-bs-toggle="tooltip" title="Eliminar"><i class="bi bi-trash"></i></a>


          </td>
        </tr>
      {% endfor %}
    {% else %}
    <h1>No hay boleterías registradas en el sistema</h1>
    <a class="btn btn-outline-success" href="{% url 'terminal:nueva_nmen' %}">Agregar boletería</a>
    {% endif %}
  </tbody>
</table>

{% endblock %}