code/altemoi/altemoi/altemoi/altemoi/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('terminal/', include('terminal.urls', namespace = "terminal")),
    path('usuarios/', include('usuarios.urls', namespace= "usuarios")),
    path('', LoginView.as_view(template_name='index.html'), name = "login"),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('reset/password_reset', PasswordResetView.as_view(template_name='registration/password_reset_form.html', email_template_name='registration/password_reset_email.html'), name = 'password_reset'),
    path('reset/password_reset_done', PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name = 'password_reset_done'),
    re_path(r'^reset/(?P<uidb64>[0-9A-za-z_\-]+)/(?P<token>.+)/$', PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name = 'password_reset_confirm'),
    path('reset/done',PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html') , name = 'password_reset_complete'),
]

code/altemoi/altemoi/altemoi/terminal/urls.py
from django.urls import include, path, re_path
from django.contrib.auth.decorators import login_required

from . import views
app_name = "terminal"

urlpatterns = [
                path('tablon', login_required(views.Tablon), name='tablon'),

                #vista de monitor de Entradas y Salidas
                path('monitor', login_required(views.Monitor), name='monitor'),
                path('vermonitor', login_required(views.VerMonitor), name='vermonitor'),
                path('nuevaterminal', login_required(views.NuevaTerminal.as_view()), name='nueva_lvidaqa'),
                path('listaterminal', login_required(views.ListaTerminal.as_view()), name='lista_lvidaqa'),
                re_path(r'^editarterminal/(?P<pk>\d+)/$', login_required(views.EditarTerminal.as_view()), name='editar_lvidaqa'),
                re_path(r'^eliminarterminal/(?P<pk>\d+)/$', login_required(views.EliminarTerminal.as_view()), name='eliminar_lvidaqa'),


                path('nuevapuerta', login_required(views.NuevaPuerta.as_view()), name='nueva_lasom'),
                path('listapuerta', login_required(views.ListaPuerta.as_view()), name='lista_lasom'),
                re_path(r'^editarpuerta/(?P<pk>\d+)/$', login_required(views.EditarPuerta.as_view()), name='editar_lasom'),
                re_path(r'^eliminarpuerta/(?P<pk>\d+)/$', login_required(views.EliminarPuerta.as_view()), name='eliminar_lasom'),


                path('nuevaplataforma', login_required(views.NuevaPlataforma.as_view()), name='nueva_lmala'),
                path('listaplataforma', login_required(views.ListaPlataforma.as_view()), name='lista_lmala'),
                re_path(r'^editarplataforma/(?P<pk>\d+)/$', login_required(views.EditarPlataforma.as_view()), name='editar_lmala'),
                re_path(r'^eliminarplataforma/(?P<pk>\d+)/$', login_required(views.EliminarPlataforma.as_view()), name='eliminar_lmala'),


                path('nuevaboleteria', login_required(views.NuevaBoleteria.as_view()), name='nueva_nmen'),
                path('listaboleteria', login_required(views.ListaBoleteria.as_view()), name='lista_nmen'),
                re_path(r'^editarboleteria/(?P<pk>\d+)/$', login_required(views.EditarBoleteria.as_view()), name='editar_nmen'),
                re_path(r'^eliminarboleteria/(?P<pk>\d+)/$', login_required(views.ElimininarBoleteria.as_view()), name='eliminar_nmen'), #falta implementar esto


                path('nuevostatus', login_required(views.NuevoStatus.as_view()), name='nuevo_status'),
                path('listastatus', login_required(views.ListaStatus.as_view()), name='lista_status'),
                re_path(r'^editarstatus/(?P<pk>\d+)/$', login_required(views.EditarStatus.as_view()), name='editar_status'),
                re_path(r'^eliminarstatus/(?P<pk>\d+)/$', login_required(views.EliminarStatus.as_view()), name='eliminar_status'),

                #paths para configuración de países, provincias, ciudades

                #países
                path('nuevopais', login_required(views.NuevoPais.as_view()), name='nuevo_alhua'),
                path('listapais', login_required(views.ListaPais.as_view()), name='lista_alhua'),
                re_path(r'^editarpais/(?P<pk>\d+)/$', login_required(views.EditarPais.as_view()), name='editar_alhua'),
                re_path(r'^eliminarpais/(?P<pk>\d+)/$', login_required(views.EliminarPais.as_view()), name='eliminar_alhua'),

                #provincias
                path('nuevaprovincia', login_required(views.NuevaProvincia.as_view()), name='nueva_alhuana'),
                path('listaprovincia', login_required(views.ListaProvincia.as_view()), name='lista_alhuana'),
                re_path(r'^editarprovincia/(?P<pk>\d+)/$', login_required(views.EditarProvincia.as_view()), name='editar_alhuana'),
                re_path(r'^eliminarprovincia/(?P<pk>\d+)/$', login_required(views.EliminarProvincia.as_view()), name='eliminar_alhuana'),

                #ciudades
                path('nuevaciudad', login_required(views.NuevaCiudad.as_view()), name='nueva_yinoyic'),
                path('listaciudad', login_required(views.ListaCiudad.as_view()), name='lista_yinoyic'),
                re_path(r'^editarciudad/(?P<pk>\d+)/$', login_required(views.EditarCiudad.as_view()), name='editar_yinoyic'),
                re_path(r'^eliminarciudad/(?P<pk>\d+)/$', login_required(views.EliminarCiudad.as_view()), name='eliminar_yinoyic'),


                #empresas de transporte
                path('nuevaempresa', login_required(views.NuevaEmpresa.as_view()), name='nueva_iqueuoxon'),
                path('listaempresa', login_required(views.ListaEmpresa.as_view()), name='lista_iqueuoxon'),
                re_path(r'^verempresa/(?P<pk>\d+)/$', login_required(views.VerEmpresa.as_view()), name='ver_iqueuoxon'),
                re_path(r'^editarempresa/(?P<pk>\d+)/$', login_required(views.EditarEmpresa.as_view()), name='editar_iqueuoxon'),
                re_path(r'^eliminarempresa/(?P<pk>\d+)/$', login_required(views.EliminarEmpresa.as_view()), name='eliminar_iqueuoxon'),

                #servicios de transporte ingresantes
                path('nuevoingreso', login_required(views.NuevoIngreso.as_view()), name='nuevo_inoxoneuo'),
                path('listaingreso', login_required(views.ListaIngreso.as_view()), name='lista_inoxoneuo'),
                re_path(r'^editaringreso/(?P<pk>\d+)/$', login_required(views.EditarIngreso.as_view()), name='editar_inoxoneuo'),
                re_path(r'^eliminaringreso/(?P<pk>\d+)/$', login_required(views.EliminarIngreso.as_view()), name='eliminar_inoxoneuo'),

                #Detalle del servicio ingresante
                #la forma de llamarla es levemente diferente porque es una vista basada en función
                path('detalleingreso/<int:id_ingreso>/', login_required(views.DetalleIngreso), name='detalle_inoxoneuo'),
                path('nuevoingresointermedio/<int:id_ingreso>/', login_required(views.NuevoIngresoIntermedio), name='nuevo_inoxoneuo_intermedio'),
                re_path(r'^eliminaringresointermedio/(?P<pk>\d+)/$', login_required(views.EliminarIngresoIntermedio.as_view()), name='eliminar_inoxoneuo_intermedio'),

                #Detalle del servicio saliente
                #la forma de llamarla es levemente diferente porque es una vista basada en función
                path('detalleegreso/<int:id_egreso>/', login_required(views.DetalleEgreso), name='detalle_deyachi'),
                path('nuevoegresointermedio/<int:id_egreso>/', login_required(views.NuevoEgresoIntermedio), name='nuevo_deyachi_intermedio'),
                re_path(r'^eliminaregresointermedio/(?P<pk>\d+)/$', login_required(views.EliminarEgresoIntermedio.as_view()), name='eliminar_deyachi_intermedio'),

                #paths para asociar empresas a boleterías
                #path('nuevaboleteriaempresa', login_required(views.NuevaBoleteriaEmpresa.as_view()), name='nuevo_nmen_iqueuoxon'),
                path('nuevaboleteriaempresa/<int:id_boleteria>/', login_required(views.NuevaBoleteriaEmpresa), name='nuevo_nmen_iqueuoxon'),
                re_path(r'^verboleteria/(?P<pk>\d+)/$', login_required(views.VerBoleteria.as_view()), name='ver_nmen'),
                path('listaboleteriaempresa/<int:id_boleteria>/', login_required(views.ListaBoleteriaEmpresa), name='lista_nmen_iqueuoxon'),
                re_path(r'^eliminarboleteriaempresa/(?P<pk>\d+)/$', login_required(views.EliminarBoleteriaEmpresa.as_view()), name='eliminar_nmen_iqueuoxon'),


                #servicios de transporte salientes
                path('nuevoegreso', login_required(views.NuevoEgreso.as_view()), name='nuevo_deyachi'),
                path('listaegreso', login_required(views.ListaEgreso.as_view()), name='lista_deyachi'),
                #path('listaegreso', login_required(views.ListaEgreso), name='lista_deyachi'),
                re_path(r'^editaregreso/(?P<pk>\d+)/$', login_required(views.EditarEgreso.as_view()), name='editar_deyachi'),
                re_path(r'^eliminaregreso/(?P<pk>\d+)/$', login_required(views.EliminarEgreso.as_view()), name='eliminar_deyachi'),



                #parámetros del Sistema
                path('nuevoparametro', login_required(views.NuevoParametro.as_view()), name='nuevo_parametro'),
                path('listaparametro', login_required(views.ListaParametro.as_view()), name='lista_parametro'),
                re_path(r'^editarparametro/(?P<pk>\d+)/$', login_required(views.EditarParametro.as_view()), name='editar_parametro'),
                re_path(r'^eliminarparametro/(?P<pk>\d+)/$', login_required(views.EliminarParametro.as_view()), name='eliminar_parametro'),

]

code/altemoi/altemoi/altemoi/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('terminal/', include('terminal.urls', namespace = "terminal")),
    path('usuarios/', include('usuarios.urls', namespace= "usuarios")),
    path('', LoginView.as_view(template_name='index.html'), name = "login"),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('reset/password_reset', PasswordResetView.as_view(template_name='registration/password_reset_form.html', email_template_name='registration/password_reset_email.html'), name = 'password_reset'),
    path('reset/password_reset_done', PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name = 'password_reset_done'),
    re_path(r'^reset/(?P<uidb64>[0-9A-za-z_\-]+)/(?P<token>.+)/$', PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name = 'password_reset_confirm'),
    path('reset/done',PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html') , name = 'password_reset_complete'),
]

code/altemoi/altemoi/altemoi/templates/iot/alhua.html
{% extends 'iot/base.html' %}

{%block titulo%}
  {% if object %}
  <h2 class="modal-title">Edición de países</h2>
  {% else %}
  <h2 class="modal-title">Nuevo país</h2>
  {% endif %}
{% endblock %}


{% block etiquetaform %}
  {% if object %}
  <form action="{% url 'terminal:editar_alhua' object.id %}" method="post">
  {% else %}
  <form action="{% url 'terminal:nuevo_alhua' %}" method="post">
    {% endif %}
{% endblock %}

code/altemoi/altemoi/altemoi/templates/iot/alhuana.html
{% extends 'iot/base.html' %}

{%block titulo%}
  {% if object %}
  <h2 class="modal-title">Edición de provincias</h2>
  {% else %}
  <h2 class="modal-title">Nueva provincia</h2>
  {% endif %}
{% endblock %}


{% block etiquetaform %}
  {% if object %}
  <form action="{% url 'terminal:editar_alhuana' object.id %}" method="post">
  {% else %}
  <form action="{% url 'terminal:nueva_alhuana' %}" method="post">
    {% endif %}
{% endblock %}

code/altemoi/altemoi/altemoi/templates/iot/base.html
<div class="modal-dialog modal-lg" role="document">
  <div class="modal-content">
    <div class="modal-header">

      {%block titulo%}

      {% endblock %}


      <button class="close" type="button" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>

      {% block etiquetaform %}

      {% endblock %}
          {% csrf_token %}
          <div class="modal-body">
            {{ form.as_p }}

          </div>
          <div class="modal-footer">
            <button class="btn btn-danger" type="button" data-dismiss="modal">Cancelar</button>
            <button class="btn btn-primary" type="submit">Guardar</button>

          </div>
      <!-- </form> -->
  </div>

</div>

code/altemoi/altemoi/altemoi/templates/iot/deyachi.html
{% extends 'iot/base.html' %}

{%block titulo%}
  {% if object %}
  <h2 class="modal-title">Edición partida</h2>
  {% else %}
  <h2 class="modal-title">Nueva partida</h2>
  {% endif %}
{% endblock %}


{% block etiquetaform %}
  {% if object %}
  <form action="{% url 'terminal:editar_deyachi' object.id %}" method="post">
  {% else %}
  <form action="{% url 'terminal:nuevo_deyachi' %}" method="post">
    {% endif %}
{% endblock %}

code/altemoi/altemoi/altemoi/templates/iot/deyachiintermedio.html
<!-- desde aca -->
<div class="modal-dialog modal-lg" role="document">
  <div class="modal-content">
    <div class="modal-header">

        <h2 class="modal-title">Agregar ciudad intermedia origen v2 {{ egreso.id }}</h2>


      <button class="close" type="button" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>

      <form method="post" enctype="multipart/form-data" action="{% url 'terminal:nuevo_deyachi_intermedio' egreso.id %}">
          {% csrf_token %}


          <div class="modal-body">

            <div class="form-group">
                <input type="text" name="{{form.deyachi.name}}" value="{{egreso.id}}">
                <select class="" name="{{form.deyachi.name}}">
                  <option value="{{egreso.id}}" selected>{{egreso.id}}</option>
                </select>

            </div>
            <div class="form-group">
                <select class="form-control" name="{{form.ciudad.name}}">
                {% for c in noAsociadas %}

                  <option value="{{c.id}}">{{c}}</option>

                {% endfor %}
              </select>

            </div>

            <div class="modal-footer">
              <button class="btn btn-danger" type="button" data-dismiss="modal">Cancelar</button>
              <button class="btn btn-primary" type="submit">Guardar</button>

            </div>
            <!-- 2022 11 25 comentado
            <div class="form-group">
              <label for="{{form.empresa.name}}">{{form.empresa.label}}</label>
                {{form.empresa}}
            </div>
            <div class="form-group">
              <label for="{{form.boleteria.name}}">{{form.boleteria.label}}</label>

              {{form.boleteria}}
            </div>

          </div>


          -->
      </form>
  </div>

</div>

code/altemoi/altemoi/altemoi/templates/iot/inoxoneuo.html
{% extends 'base/base.html'  %}

{% block contenido %}
<h3>Carga de entradas</h3>
<div class="container">
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <div class="mt-4 p-5 bg-secondary  rounded">
      <h3>Ciudades intermedias</h3>
        <div>
          <a class="btn btn-success" href="#" name="button">Agregar ciudad intermedia</a>
        </div>

        <table id="tabla" class='table table-striped'>
          <thead>
            <tr>
            <td>#</td>
            <td>Ciudad</td>
            <td>Acciones</td>
          </tr>
        </thead>
        <tbody>
        </tbody>
      </table>
    </div>
    <button type="submit" class="btn btn-outline-success" name="button">Guardar servicio ingresante</button>

  </form>
</div>
{% endblock %}

code/altemoi/altemoi/altemoi/templates/iot/inoxoneuointermedio.html
<!-- desde aca -->
<div class="modal-dialog modal-lg" role="document">
  <div class="modal-content">
    <div class="modal-header">

        <h2 class="modal-title">Agregar ciudad intermedia origen v2 {{ ingreso.id }}</h2>


      <button class="close" type="button" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>

      <form method="post" enctype="multipart/form-data" action="{% url 'terminal:nuevo_inoxoneuo_intermedio' ingreso.id %}">
          {% csrf_token %}


          <div class="modal-body">

            <div class="form-group">
                <input type="text" name="{{form.inoxoneuo.name}}" value="{{ingreso.id}}">
                <select class="" name="{{form.inoxoneuo.name}}">
                  <option value="{{ingreso.id}}" selected>{{ingreso.id}}</option>
                </select>

            </div>
            <div class="form-group">
                <select class="form-control" name="{{form.ciudad.name}}">
                {% for c in noAsociadas %}

                  <option value="{{c.id}}">{{c}}</option>

                {% endfor %}
              </select>

            </div>

            <div class="modal-footer">
              <button class="btn btn-danger" type="button" data-dismiss="modal">Cancelar</button>
              <button class="btn btn-primary" type="submit">Guardar</button>

            </div>
            <!-- 2022 11 25 comentado
            <div class="form-group">
              <label for="{{form.empresa.name}}">{{form.empresa.label}}</label>
                {{form.empresa}}
            </div>
            <div class="form-group">
              <label for="{{form.boleteria.name}}">{{form.boleteria.label}}</label>

              {{form.boleteria}}
            </div>

          </div>


          -->
      </form>
  </div>

</div>

code/altemoi/altemoi/altemoi/templates/iot/lasom.html
<div class="modal-dialog modal-lg" role="document">
  <div class="modal-content">
    <div class="modal-header">
      {% if object %}
      <h2 class="modal-title">Edición puerta de embarque</h2>
      {% else %}
      <h2 class="modal-title">Nueva puerta de embarque</h2>
      {% endif %}

      <button class="close" type="button" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
      {% if object %}
      <form action="{% url 'terminal:editar_lasom' object.id %}" method="post">
      {% else %}
      <form action="{% url 'terminal:nueva_lasom' %}" method="post">
      {% endif %}

          {% csrf_token %}
          <div class="modal-body">
            {{ form.as_p }}

          </div>
          <div class="modal-footer">
            <button class="btn btn-danger" type="button" data-dismiss="modal">Cancelar</button>
            <button class="btn btn-primary" type="submit">Guardar</button>

          </div>
      </form>
  </div>

</div>

code/altemoi/altemoi/altemoi/templates/iot/lmala.html
{% extends 'base/base.html'  %}

{% block contenido %}
<h3>Carga de plataformas</h3>
<div class="container">
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit" class="btn btn-outline-success" name="button">Guardar plataforma</button>
  </form>
</div>
{% endblock %}

code/altemoi/altemoi/altemoi/templates/iot/lvidaqa.html
{% extends 'base/base.html'  %}

{% block contenido %}
<h3>Carga de estación terminal</h3>

<form method="post">
  {% csrf_token %}
  {{ form.as_p }}

  <button type="submit" class="btn btn-outline-success" name="button">Guardar estación</button>
</form>
{% endblock %}

code/altemoi/altemoi/altemoi/templates/iot/nmen.html
{% extends 'base/base.html'  %}

{% block contenido %}
<h3>Carga de boleterías</h3>

<div class="container">
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit" class="btn btn-outline-success" name="button">Guardar boletería</button>
  </form>
</div>
{% endblock %}

code/altemoi/altemoi/altemoi/templates/iot/nmeniqueuoxon.html
<!-- desde aca -->
<div class="modal-dialog modal-lg" role="document">
  <div class="modal-content">
    <div class="modal-header">

        <h2 class="modal-title">Asociar empresa v2 {{ boleteria.id }}</h2>


      <button class="close" type="button" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>

      <form method="post" enctype="multipart/form-data" action="{% url 'terminal:nuevo_nmen_iqueuoxon' boleteria.id %}">
          {% csrf_token %}


          <div class="modal-body">

            <div class="form-group">
                <input type="text" name="{{form.boleteria.name}}" value="{{boleteria.id}}">
                <select class="" name="{{form.boleteria.name}}">
                  <option value="{{boleteria.id}}" selected>{{boleteria.id}}</option>
                </select>

            </div>
            <div class="form-group">
                <select class="" name="{{form.empresa.name}}">
                {% for e in noAsociadas %}

                  <option value="{{e.id}}">{{e}}</option>

                {% endfor %}
              </select>

            </div>

            <div class="modal-footer">
              <button class="btn btn-danger" type="button" data-dismiss="modal">Cancelar</button>
              <button class="btn btn-primary" type="submit">Guardar</button>

            </div>
            <!-- 2022 11 25 comentado
            <div class="form-group">
              <label for="{{form.empresa.name}}">{{form.empresa.label}}</label>
                {{form.empresa}}
            </div>
            <div class="form-group">
              <label for="{{form.boleteria.name}}">{{form.boleteria.label}}</label>

              {{form.boleteria}}
            </div>

          </div>


          -->
      </form>
  </div>

</div>

code/altemoi/altemoi/altemoi/templates/iot/status.html
{% extends 'iot/base.html' %}

{%block titulo%}
  {% if object %}
  <h2 class="modal-title">Edición estado de boletería</h2>
  {% else %}
  <h2 class="modal-title">Nuevo estado de boletería</h2>
  {% endif %}
{% endblock %}


{% block etiquetaform %}
  {% if object %}
  <form action="{% url 'terminal:editar_status' object.id %}" method="post">
  {% else %}
  <form action="{% url 'terminal:nuevo_status' %}" method="post">
    {% endif %}
{% endblock %}

code/altemoi/altemoi/altemoi/templates/iot/yinoyic.html
{% extends 'iot/base.html' %}

{%block titulo%}
  {% if object %}
  <h2 class="modal-title">Edición de ciudades</h2>
  {% else %}
  <h2 class="modal-title">Nueva ciudad</h2>
  {% endif %}
{% endblock %}


{% block etiquetaform %}
  {% if object %}
  <form action="{% url 'terminal:editar_yinoyic' object.id %}" method="post">
  {% else %}
  <form action="{% url 'terminal:nueva_yinoyic' %}" method="post">
    {% endif %}
{% endblock %}